site_name: DevOpsKube
site_author: DevOpsKube Team
site_description: DevOpsKube - a full SDLC Stack for Kubernetes
google_analytics: ['UA-85985871-1', 'auto']
theme: readthedocs
copyright: (c) 2016- by the DevOpsKube Team
repo_url: https://github.com/devopskube/devopskube/
pages:
- Home: 'index.md'
- Setup:
  - 'Setup Single Node': 'setup/single-node.md'
  - 'Setup Helm': 'setup/helm.md'
  - 'Setup Redmine SSO': 'setup/redmine-keycloak.md'
  - 'Setup Jenkins SSO': 'setup/jenkins-keycloak.md'
  - 'Setup Minikube': 'setup/minikube.md'
  - 'Setup Components': 'setup/components.md'
- Components:
  - 'Gogs': 'components/gogs.md'
  - 'Jenkins': 'components/jenkins.md'
  - 'Keycloak': 'components/keycloak.md'
  - 'Kube-Lego': 'components/kube-lego.md'
  - 'MySQL': 'components/mysql.md'
  - 'TheNexus': 'components/nexus.md'
  - 'Redmine': 'components/redmine.md'
  - 'SonarQube': 'components/sonarqube.md'
- About:
  - 'License': 'about/license.md'
  - 'Team': 'about/team.md'
  - 'Release Notes': 'about/release-notes.md'
  - 'Roadmap': 'about/roadmap.md'
extra:
  version: 0.1
