apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: {{ template "fullname" . }}
  labels:
    app: "{{ .Chart.Name }}"
    heritage: {{.Release.Service | quote }}
    release: {{.Release.Name | quote }}
    chart: "{{.Chart.Name}}-{{.Chart.Version}}"
    provider: devopskube
  annotations:
    kubernetes.io/ingress.class: "nginx"
    certmanager.k8s.io/issuer: {{ .Values.issuer.name | quote }}
    certmanager.k8s.io/acme-challenge-type: http01
spec:
  tls:
  - secretName: {{ .Chart.Name }}-tls
    hosts:
    - {{ .Values.hostName }}
  rules:
  - host: {{ .Values.hostName }}
    http:
      paths:
      - path: /
        backend:
          serviceName: {{ template "fullname" . }}
          servicePort: 80
